spring:
  application:
    name: api-gateway
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8181/realms/spring-microservices-realm


springdoc:
  swagger-ui:
    path: /swagger-ui.html
    enabled: true
    urls:
      - name: Product Service
        url: /aggregate/product-service/v3/api-docs
      - name: Order Service
        url: /aggregate/order-service/v3/api-docs
      - name: Inventory Service
        url: /aggregate/inventory-service/v3/api-docs

server:
  port: 9000

services:
  product:
    url: ${PRODUCT_SERVICE_URL:http://localhost:8081}
  order:
    url: ${ORDER_SERVICE_URL:http://localhost:8085}
  inventory:
    url: ${INVENTORY_SERVICE_URL:http://localhost:8084}

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: never