spring:
  application:
    name: inventory-service

  datasource:
    url: ${INVENTORY_DB_URL:jdbc:mysql://localhost:3306/inventory_service}
    username: ${INVENTORY_DB_USER:inventory_user}
    password: ${INVENTORY_DB_PASSWORD:inventory_pass}

  jpa:
    hibernate:
      ddl-auto: none

springdoc:
  swagger-ui:
    path: /swagger-ui.html
  api-docs:
    path: /api-docs

server:
  port: 8084

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: never